apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    canary:
      analysis:
        templates:
        - templateName: nginx-analysis-template
        args:
        - name: service-name
          value: metrics-generator-service
      steps:
      - setWeight: 20
      - pause: {duration: 60s}
      - setWeight: 40
      - pause: {duration: 60s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80


---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: nginx-analysis-template
spec:
  args:
  - name: service-name
  metrics:
  - name: custom-metric-success-rate
    interval: 20s
    successCondition: result > 0.80
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(http_requests_total{service="{{args.service-name}}"}[5m])) 
          /
          sum(rate(http_requests_total{service="{{args.service-name}}", status="success"}[5m]))

